-- ============================================================
-- 02_raw_data_ingestion.sql
-- Zomato Data ETL & Analytics Pipeline
-- ============================================================
-- Purpose:
--   Create the raw landing table, inspect the staged CSV and ingest
--   the source data from AWS S3 into Snowflake.
-- ============================================================

CREATE OR REPLACE TABLE RAW.STAGE_RAW_DATA (
    URL             STRING,
    ADDRESS         STRING,
    NAME            STRING,
    ONLINE_ORDER    STRING,
    BOOK_TABLE      STRING,
    RATE            STRING,
    VOTES           STRING,
    PHONE           STRING,
    LOCATION        STRING,
    REST_TYPE       STRING,
    DISH_LIKED      STRING,
    CUISINES        STRING,
    APPROX_COST     STRING,
    REVIEWS_LIST    STRING,
    MENU_ITEM       STRING,
    LISTED_IN_TYPE  STRING,
    LISTED_IN_CITY  STRING
);

COPY INTO RAW.STAGE_RAW_DATA
FROM @RAW.MANAGE_STAGE/zomato.csv
FILE_FORMAT = (
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    MULTI_LINE = TRUE
)
ON_ERROR = 'ABORT_STATEMENT';

SELECT COUNT(*) AS TOTAL_ROWS
FROM RAW.STAGE_RAW_DATA;

SELECT *
FROM RAW.STAGE_RAW_DATA
LIMIT 5;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(NAME) AS NAME_FILLED,
    COUNT(CUISINES) AS CUISINES_FILLED,
    COUNT(RATE) AS RATE_FILLED,
    COUNT(VOTES) AS VOTES_FILLED,
    COUNT(APPROX_COST) AS COST_FILLED
FROM RAW.STAGE_RAW_DATA;

SELECT
    RATE,
    COUNT(*) AS ROW_COUNT
FROM RAW.STAGE_RAW_DATA
GROUP BY RATE
ORDER BY ROW_COUNT DESC
LIMIT 30;

SELECT
    APPROX_COST,
    COUNT(*) AS ROW_COUNT
FROM RAW.STAGE_RAW_DATA
GROUP BY APPROX_COST
ORDER BY ROW_COUNT DESC
LIMIT 20;

SELECT
    ONLINE_ORDER,
    BOOK_TABLE,
    COUNT(*) AS ROW_COUNT
FROM RAW.STAGE_RAW_DATA
GROUP BY ONLINE_ORDER, BOOK_TABLE
ORDER BY ROW_COUNT DESC;

SELECT
    RATE,
    COUNT(*) AS ROW_COUNT
FROM RAW.STAGE_RAW_DATA
GROUP BY RATE
ORDER BY ROW_COUNT DESC
LIMIT 30;

SELECT
    APPROX_COST,
    COUNT(*) AS ROW_COUNT
FROM RAW.STAGE_RAW_DATA
GROUP BY APPROX_COST
ORDER BY ROW_COUNT DESC
LIMIT 20;
