-- ============================================================
-- 03_cleaning_and_transformation.sql
-- Zomato Data ETL & Analytics Pipeline
-- ============================================================
-- Purpose:
--   Clean raw Zomato data and convert text fields into analytics-ready
--   numeric/boolean values.
--
-- NOTE:
--   The second ZOMATO_CLEAN definition below is the improved/final
--   version from the original project. It extracts decimal ratings
--   with REGEXP_SUBSTR and handles 'NEW'/blank ratings as NULL.
-- ============================================================

-- Initial cleaning version / exploration
CREATE OR REPLACE TABLE ZOMATO_CLEAN AS
SELECT
    URL,
    TRIM(ADDRESS) AS ADDRESS,
    TRIM(NAME) AS RESTAURANT_NAME,

    CASE
        WHEN LOWER(TRIM(ONLINE_ORDER)) = 'yes' THEN TRUE
        WHEN LOWER(TRIM(ONLINE_ORDER)) = 'no' THEN FALSE
        ELSE NULL
    END AS ONLINE_ORDER,

    CASE
        WHEN LOWER(TRIM(BOOK_TABLE)) = 'yes' THEN TRUE
        WHEN LOWER(TRIM(BOOK_TABLE)) = 'no' THEN FALSE
        ELSE NULL
    END AS BOOK_TABLE,

    CASE
        WHEN TRIM(RATE) IN ('', 'NEW') THEN NULL
        ELSE TRY_TO_NUMBER(
            SPLIT_PART(REPLACE(TRIM(RATE), ' ', ''), '/', 1)
        )
    END AS RATING,

    TRY_TO_NUMBER(
        REPLACE(TRIM(VOTES), ',', '')
    ) AS VOTES,

    TRIM(PHONE) AS PHONE,

    TRIM(LOCATION) AS LOCATION,

    TRIM(REST_TYPE) AS REST_TYPE,

    TRIM(DISH_LIKED) AS DISH_LIKED,

    TRIM(CUISINES) AS CUISINES,

    TRY_TO_NUMBER(
        REPLACE(TRIM(APPROX_COST), ',', '')
    ) AS APPROX_COST,

    REVIEWS_LIST,

    MENU_ITEM,

    TRIM(LISTED_IN_TYPE) AS LISTED_IN_TYPE,

    TRIM(LISTED_IN_CITY) AS LISTED_IN_CITY

FROM STAGE_RAW_DATA;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(RESTAURANT_NAME IS NOT NULL) AS NAME_FILLED,
    COUNT_IF(CUISINES IS NOT NULL) AS CUISINES_FILLED,
    COUNT_IF(RATING IS NOT NULL) AS RATING_FILLED,
    COUNT_IF(VOTES IS NOT NULL) AS VOTES_FILLED,
    COUNT_IF(APPROX_COST IS NOT NULL) AS COST_FILLED
FROM ZOMATO_CLEAN;


SELECT RATING, COUNT(*) AS ROW_COUNT
FROM ZOMATO_CLEAN
GROUP BY RATING
ORDER BY RATING DESC;

SELECT APPROX_COST, COUNT(*) AS ROW_COUNT
FROM ZOMATO_CLEAN
GROUP BY APPROX_COST
ORDER BY APPROX_COST;

DESC TABLE ZOMATO_CLEAN;

SELECT
    RATE,
    TRY_TO_DECIMAL(
        REGEXP_SUBSTR(TRIM(RATE), '[0-9]+(\.[0-9]+)?'),
        3,
        1
    ) AS TEST_RATING
FROM STAGE_RAW_DATA
WHERE TRIM(RATE) NOT IN ('', 'NEW')
LIMIT 30;

-- ============================================================
-- Final cleaning and transformation
-- ============================================================

CREATE OR REPLACE TABLE ZOMATO_CLEAN AS
SELECT
    URL,
    TRIM(ADDRESS) AS ADDRESS,
    TRIM(NAME) AS RESTAURANT_NAME,

    CASE
        WHEN LOWER(TRIM(ONLINE_ORDER)) = 'yes' THEN TRUE
        WHEN LOWER(TRIM(ONLINE_ORDER)) = 'no' THEN FALSE
        ELSE NULL
    END AS ONLINE_ORDER,

    CASE
        WHEN LOWER(TRIM(BOOK_TABLE)) = 'yes' THEN TRUE
        WHEN LOWER(TRIM(BOOK_TABLE)) = 'no' THEN FALSE
        ELSE NULL
    END AS BOOK_TABLE,

    CASE
        WHEN TRIM(RATE) IN ('', 'NEW') THEN NULL
        ELSE TRY_TO_NUMBER(
            SPLIT_PART(REPLACE(TRIM(RATE), ' ', ''), '/', 1)
        )
    END AS RATING,

    TRY_TO_NUMBER(
        REPLACE(TRIM(VOTES), ',', '')
    ) AS VOTES,

    TRIM(PHONE) AS PHONE,

    TRIM(LOCATION) AS LOCATION,

    TRIM(REST_TYPE) AS REST_TYPE,

    TRIM(DISH_LIKED) AS DISH_LIKED,

    TRIM(CUISINES) AS CUISINES,

    TRY_TO_NUMBER(
        REPLACE(TRIM(APPROX_COST), ',', '')
    ) AS APPROX_COST,

    REVIEWS_LIST,

    MENU_ITEM,

    TRIM(LISTED_IN_TYPE) AS LISTED_IN_TYPE,

    TRIM(LISTED_IN_CITY) AS LISTED_IN_CITY

FROM STAGE_RAW_DATA;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(RESTAURANT_NAME IS NOT NULL) AS NAME_FILLED,
    COUNT_IF(CUISINES IS NOT NULL) AS CUISINES_FILLED,
    COUNT_IF(RATING IS NOT NULL) AS RATING_FILLED,
    COUNT_IF(VOTES IS NOT NULL) AS VOTES_FILLED,
    COUNT_IF(APPROX_COST IS NOT NULL) AS COST_FILLED
FROM ZOMATO_CLEAN;


SELECT RATING, COUNT(*) AS ROW_COUNT
FROM ZOMATO_CLEAN
GROUP BY RATING
ORDER BY RATING DESC;

SELECT APPROX_COST, COUNT(*) AS ROW_COUNT
FROM ZOMATO_CLEAN
GROUP BY APPROX_COST
ORDER BY APPROX_COST;

DESC TABLE ZOMATO_CLEAN;

SELECT
    RATE,
    TRY_TO_DECIMAL(
        REGEXP_SUBSTR(TRIM(RATE), '[0-9]+(\.[0-9]+)?'),
        3,
        1
    ) AS TEST_RATING
FROM STAGE_RAW_DATA
WHERE TRIM(RATE) NOT IN ('', 'NEW')
LIMIT 30;


CREATE OR REPLACE TABLE ZOMATO_CLEAN AS
SELECT
    URL,
    TRIM(ADDRESS) AS ADDRESS,
    TRIM(NAME) AS RESTAURANT_NAME,

    CASE
        WHEN LOWER(TRIM(ONLINE_ORDER)) = 'yes' THEN TRUE
        WHEN LOWER(TRIM(ONLINE_ORDER)) = 'no' THEN FALSE
        ELSE NULL
    END AS ONLINE_ORDER,

    CASE
        WHEN LOWER(TRIM(BOOK_TABLE)) = 'yes' THEN TRUE
        WHEN LOWER(TRIM(BOOK_TABLE)) = 'no' THEN FALSE
        ELSE NULL
    END AS BOOK_TABLE,

    CASE
        WHEN TRIM(RATE) = '' OR UPPER(TRIM(RATE)) = 'NEW' THEN NULL
        ELSE TRY_TO_DECIMAL(
            REGEXP_SUBSTR(
                TRIM(RATE),
                '[0-9]+(\.[0-9]+)?'
            ),
            3,
            1
        )
    END AS RATING,

    TRY_TO_NUMBER(
        REPLACE(TRIM(VOTES), ',', '')
    ) AS VOTES,

    TRIM(PHONE) AS PHONE,
    TRIM(LOCATION) AS LOCATION,
    TRIM(REST_TYPE) AS REST_TYPE,
    TRIM(DISH_LIKED) AS DISH_LIKED,
    TRIM(CUISINES) AS CUISINES,

    TRY_TO_NUMBER(
        REPLACE(TRIM(APPROX_COST), ',', '')
    ) AS APPROX_COST,

    REVIEWS_LIST,
    MENU_ITEM,
    TRIM(LISTED_IN_TYPE) AS LISTED_IN_TYPE,
    TRIM(LISTED_IN_CITY) AS LISTED_IN_CITY

FROM STAGE_RAW_DATA;

-- Basic validation after transformation
SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(RATING) AS RATING_FILLED,
    COUNT(VOTES) AS VOTES_FILLED,
    COUNT(APPROX_COST) AS COST_FILLED,
    COUNT(CUISINES) AS CUISINES_FILLED
FROM ZOMATO_CLEAN;

SELECT
    RATING,
    COUNT(*) AS ROW_COUNT
FROM ZOMATO_CLEAN
GROUP BY RATING
ORDER BY RATING DESC;

SELECT
    APPROX_COST,
    COUNT(*) AS ROW_COUNT
FROM ZOMATO_CLEAN
GROUP BY APPROX_COST;

DESCRIBE TABLE ZOMATO_CLEAN;

SELECT *
FROM ZOMATO_CLEAN
LIMIT 5;
