-- ============================================================
-- 04_star_schema.sql
-- Zomato Data ETL & Analytics Pipeline
-- ============================================================
-- Purpose:
--   Build the dimensional model:
--     DIM_RESTAURANT
--     DIM_LOCATION
--     DIM_CUISINE
--     DIM_TYPE
--     FACT_RESTAURANT
--
-- Source:
--   ZOMATO_CLEAN
-- ============================================================

// Create DIM_RESTAURANT

CREATE OR REPLACE TABLE DIM_RESTAURANT (
    RESTAURANT_ID INT AUTOINCREMENT PRIMARY KEY,
    URL STRING,
    RESTAURANT_NAME STRING,
    ADDRESS STRING,
    PHONE STRING
);

INSERT INTO DIM_RESTAURANT (
    URL,
    RESTAURANT_NAME,
    ADDRESS,
    PHONE
)
SELECT DISTINCT
    TRIM(URL),
    TRIM(RESTAURANT_NAME),
    TRIM(ADDRESS),
    TRIM(PHONE)
FROM ZOMATO_CLEAN
WHERE RESTAURANT_NAME IS NOT NULL;

SELECT COUNT(*) AS RESTAURANT_DIM_ROWS
FROM DIM_RESTAURANT;

SELECT *
FROM DIM_RESTAURANT
LIMIT 10;

//Dim_location

CREATE OR REPLACE TABLE DIM_LOCATION (
    LOCATION_ID INT AUTOINCREMENT PRIMARY KEY,
    LOCATION STRING,
    LISTED_IN_CITY STRING
);

INSERT INTO DIM_LOCATION (
    LOCATION,
    LISTED_IN_CITY
)
SELECT DISTINCT
    TRIM(LOCATION),
    TRIM(LISTED_IN_CITY)
FROM ZOMATO_CLEAN
WHERE LOCATION IS NOT NULL
   OR LISTED_IN_CITY IS NOT NULL;

   SELECT COUNT(*) AS LOCATION_DIM_ROWS
FROM DIM_LOCATION;

SELECT *
FROM DIM_LOCATION
LIMIT 10;

//DIM_CUISINE

CREATE OR REPLACE TABLE DIM_CUISINE (
    CUISINE_ID INT AUTOINCREMENT PRIMARY KEY,
    DISH_LIKED STRING,
    CUISINES STRING
);

INSERT INTO DIM_CUISINE (
    DISH_LIKED,
    CUISINES
)
SELECT DISTINCT
    TRIM(DISH_LIKED),
    TRIM(CUISINES)
FROM ZOMATO_CLEAN
WHERE DISH_LIKED IS NOT NULL
   OR CUISINES IS NOT NULL;

   SELECT COUNT(*) AS CUISINE_DIM_ROWS
FROM DIM_CUISINE;

SELECT *
FROM DIM_CUISINE
LIMIT 10;

//DIM_TYPE

CREATE OR REPLACE TABLE DIM_TYPE (
    TYPE_ID INT AUTOINCREMENT PRIMARY KEY,
    REST_TYPE STRING,
    LISTED_IN_TYPE STRING
);

INSERT INTO DIM_TYPE (
    REST_TYPE,
    LISTED_IN_TYPE
)
SELECT DISTINCT
    TRIM(REST_TYPE),
    TRIM(LISTED_IN_TYPE)
FROM ZOMATO_CLEAN
WHERE REST_TYPE IS NOT NULL
   OR LISTED_IN_TYPE IS NOT NULL;

   SELECT COUNT(*) AS TYPE_DIM_ROWS
FROM DIM_TYPE;

SELECT *
FROM DIM_TYPE
LIMIT 10;

//FACT table

CREATE OR REPLACE TABLE FACT_RESTAURANT (
    FACT_ID INT AUTOINCREMENT PRIMARY KEY,
    RESTAURANT_ID INT,
    LOCATION_ID INT,
    CUISINE_ID INT,
    TYPE_ID INT,

    ONLINE_ORDER BOOLEAN,
    BOOK_TABLE BOOLEAN,

    RATING NUMBER(3,1),
    VOTES NUMBER(38,0),
    APPROX_COST NUMBER(38,0)
);
//populate fact table

INSERT INTO FACT_RESTAURANT (
    RESTAURANT_ID,
    LOCATION_ID,
    CUISINE_ID,
    TYPE_ID,
    ONLINE_ORDER,
    BOOK_TABLE,
    RATING,
    VOTES,
    APPROX_COST
)
SELECT
    DR.RESTAURANT_ID,
    DL.LOCATION_ID,
    DC.CUISINE_ID,
    DT.TYPE_ID,

    Z.ONLINE_ORDER,
    Z.BOOK_TABLE,
    Z.RATING,
    Z.VOTES,
    Z.APPROX_COST

FROM ZOMATO_CLEAN Z

LEFT JOIN DIM_RESTAURANT DR
    ON TRIM(Z.URL) = DR.URL

LEFT JOIN DIM_LOCATION DL
    ON COALESCE(TRIM(Z.LOCATION), '') =
       COALESCE(DL.LOCATION, '')
   AND COALESCE(TRIM(Z.LISTED_IN_CITY), '') =
       COALESCE(DL.LISTED_IN_CITY, '')

LEFT JOIN DIM_CUISINE DC
    ON COALESCE(TRIM(Z.DISH_LIKED), '') =
       COALESCE(DC.DISH_LIKED, '')
   AND COALESCE(TRIM(Z.CUISINES), '') =
       COALESCE(DC.CUISINES, '')

LEFT JOIN DIM_TYPE DT
    ON COALESCE(TRIM(Z.REST_TYPE), '') =
       COALESCE(DT.REST_TYPE, '')
   AND COALESCE(TRIM(Z.LISTED_IN_TYPE), '') =
       COALESCE(DT.LISTED_IN_TYPE, '');

       SELECT COUNT(*) AS FACT_ROWS
FROM FACT_RESTAURANT;

SELECT *
FROM FACT_RESTAURANT
LIMIT 10;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(RESTAURANT_ID IS NULL) AS MISSING_RESTAURANT,
    COUNT_IF(LOCATION_ID IS NULL) AS MISSING_LOCATION,
    COUNT_IF(CUISINE_ID IS NULL) AS MISSING_CUISINE,
    COUNT_IF(TYPE_ID IS NULL) AS MISSING_TYPE
FROM FACT_RESTAURANT;
