-- ============================================================
-- 06_business_analytics.sql
-- Zomato Data ETL & Analytics Pipeline
-- ============================================================
-- Purpose:
--   Business-focused SQL analytics for restaurant performance,
--   affordability, locations, online ordering, table booking,
--   ratings, cost segments and restaurant types.
-- ============================================================

// Analytics Use Case 1: Top-Rated Restaurants
SELECT
    DR.RESTAURANT_NAME,
    DL.LOCATION,
    DC.CUISINES,
    FR.RATING,
    FR.VOTES,
    FR.APPROX_COST
FROM FACT_RESTAURANT FR
JOIN DIM_RESTAURANT DR
    ON FR.RESTAURANT_ID = DR.RESTAURANT_ID
LEFT JOIN DIM_LOCATION DL
    ON FR.LOCATION_ID = DL.LOCATION_ID
LEFT JOIN DIM_CUISINE DC
    ON FR.CUISINE_ID = DC.CUISINE_ID
WHERE FR.RATING IS NOT NULL
ORDER BY FR.RATING DESC, FR.VOTES DESC
LIMIT 20;


//Analytics Use Case 2: Best Restaurants Under ₹500
SELECT
    DR.RESTAURANT_NAME,
    DL.LOCATION,
    DC.CUISINES,
    FR.RATING,
    FR.VOTES,
    FR.APPROX_COST
FROM FACT_RESTAURANT FR
JOIN DIM_RESTAURANT DR
    ON FR.RESTAURANT_ID = DR.RESTAURANT_ID
LEFT JOIN DIM_LOCATION DL
    ON FR.LOCATION_ID = DL.LOCATION_ID
LEFT JOIN DIM_CUISINE DC
    ON FR.CUISINE_ID = DC.CUISINE_ID
WHERE FR.APPROX_COST <= 500
  AND FR.RATING IS NOT NULL
ORDER BY FR.RATING DESC, FR.VOTES DESC
LIMIT 20;

//Analytics Use Case 3: Online Order vs Table Booking

SELECT
    ONLINE_ORDER,
    BOOK_TABLE,
    COUNT(*) AS RESTAURANT_COUNT
FROM FACT_RESTAURANT
GROUP BY
    ONLINE_ORDER,
    BOOK_TABLE
ORDER BY RESTAURANT_COUNT DESC;

//Analytics Use Case 4: Restaurant Count by Location

SELECT
    DL.LOCATION,
    COUNT(*) AS RESTAURANT_COUNT
FROM FACT_RESTAURANT FR
JOIN DIM_LOCATION DL
    ON FR.LOCATION_ID = DL.LOCATION_ID
WHERE DL.LOCATION IS NOT NULL
GROUP BY DL.LOCATION
ORDER BY RESTAURANT_COUNT DESC
LIMIT 20;



SELECT *
FROM ZOMATO_PROJECT.RAW.ZOMATO_CLEAN
LIMIT 10;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT RESTAURANT_NAME || '|' || LOCATION) AS UNIQUE_RESTAURANT_LOCATIONS
FROM ZOMATO_PROJECT.RAW.ZOMATO_CLEAN;

CREATE OR REPLACE TABLE ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT AS
SELECT *
FROM ZOMATO_PROJECT.RAW.ZOMATO_CLEAN
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY RESTAURANT_NAME, LOCATION
    ORDER BY VOTES DESC
) = 1;
SELECT COUNT(*) AS UNIQUE_RESTAURANTS
FROM ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT;

SELECT
    COUNT(*) AS TOTAL_RESTAURANTS,
    COUNT(DISTINCT RESTAURANT_NAME) AS UNIQUE_NAMES,
    COUNT(DISTINCT LOCATION) AS UNIQUE_LOCATIONS
FROM ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT;

SELECT
    RESTAURANT_NAME,
    LOCATION,
    COUNT(*) AS CNT
FROM ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT
GROUP BY RESTAURANT_NAME, LOCATION
HAVING COUNT(*) > 1
ORDER BY CNT DESC;

//Use Case 1 — Online Order vs Table Booking

SELECT
    ONLINE_ORDER,
    BOOK_TABLE,
    COUNT(*) AS RESTAURANT_COUNT
FROM ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT
GROUP BY ONLINE_ORDER, BOOK_TABLE
ORDER BY RESTAURANT_COUNT DESC;

//use case 2 :Best value resturant 
 SELECT
    RESTAURANT_NAME,
    LOCATION,
    RATING,
    VOTES,
    APPROX_COST
FROM ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT
WHERE RATING >= 4.0
  AND VOTES >= 500
  AND APPROX_COST IS NOT NULL
ORDER BY
    APPROX_COST ASC,
    RATING DESC,
    VOTES DESC
LIMIT 20;

//Use Case 3 — Location with Most Restaurants
SELECT
    LOCATION,
    COUNT(*) AS RESTAURANT_COUNT,
    ROUND(AVG(RATING), 2) AS AVG_RATING,
    ROUND(AVG(APPROX_COST), 0) AS AVG_COST
FROM ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT
GROUP BY LOCATION
ORDER BY RESTAURANT_COUNT DESC
LIMIT 20;

//Use Case 4 — Best Locations by Rating

SELECT
    LOCATION,
    COUNT(*) AS RESTAURANT_COUNT,
    ROUND(AVG(RATING), 2) AS AVG_RATING
FROM ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT
WHERE RATING IS NOT NULL
GROUP BY LOCATION
HAVING COUNT(*) >= 20
ORDER BY AVG_RATING DESC
LIMIT 15;

//Use Case 5 — Online Ordering Adoption by Location
SELECT
    LOCATION,
    COUNT(*) AS TOTAL_RESTAURANTS,
    SUM(IFF(ONLINE_ORDER = TRUE, 1, 0)) AS ONLINE_ORDER_RESTAURANTS,
    ROUND(
        100.0 * SUM(IFF(ONLINE_ORDER = TRUE, 1, 0)) / COUNT(*),
        2
    ) AS ONLINE_ORDER_PERCENT
FROM ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT
GROUP BY LOCATION
HAVING COUNT(*) >= 20
ORDER BY ONLINE_ORDER_PERCENT DESC
LIMIT 20;

//Use Case 6 — Table Booking Adoption

SELECT
    LOCATION,
    COUNT(*) AS TOTAL_RESTAURANTS,
    SUM(IFF(BOOK_TABLE = TRUE, 1, 0)) AS BOOKING_RESTAURANTS,
    ROUND(
        100.0 * SUM(IFF(BOOK_TABLE = TRUE, 1, 0)) / COUNT(*),
        2
    ) AS BOOKING_PERCENT
FROM ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT
GROUP BY LOCATION
HAVING COUNT(*) >= 20
ORDER BY BOOKING_PERCENT DESC
LIMIT 20;

//Use Case 7 — Rating Distribution

SELECT
    RATING,
    COUNT(*) AS RESTAURANT_COUNT
FROM ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT
WHERE RATING IS NOT NULL
GROUP BY RATING
ORDER BY RATING DESC;

//Use Case 8 — Cost Segment Analysis
SELECT
    CASE
        WHEN APPROX_COST < 300 THEN 'Budget (<300)'
        WHEN APPROX_COST BETWEEN 300 AND 700 THEN 'Mid-Range (300-700)'
        WHEN APPROX_COST BETWEEN 701 AND 1200 THEN 'Premium (701-1200)'
        ELSE 'Luxury (>1200)'
    END AS COST_SEGMENT,

    COUNT(*) AS RESTAURANT_COUNT,
    ROUND(AVG(RATING), 2) AS AVG_RATING,
    ROUND(AVG(VOTES), 0) AS AVG_VOTES

FROM ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT
WHERE APPROX_COST IS NOT NULL
GROUP BY COST_SEGMENT
ORDER BY AVG_RATING DESC;

//Use Case 9 — Restaurant Type Performance
SELECT
    REST_TYPE,
    COUNT(*) AS RESTAURANT_COUNT,
    ROUND(AVG(RATING), 2) AS AVG_RATING,
    ROUND(AVG(APPROX_COST), 0) AS AVG_COST,
    ROUND(AVG(VOTES), 0) AS AVG_VOTES
FROM ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT
WHERE REST_TYPE IS NOT NULL
GROUP BY REST_TYPE
HAVING COUNT(*) >= 20
ORDER BY AVG_RATING DESC;

//Use Case 10 — Highly Rated but Affordable
SELECT
    RESTAURANT_NAME,
    LOCATION,
    REST_TYPE,
    RATING,
    VOTES,
    APPROX_COST
FROM ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT
WHERE RATING >= 4.5
  AND APPROX_COST <= 500
  AND VOTES >= 100
ORDER BY RATING DESC, VOTES DESC, APPROX_COST ASC
LIMIT 25;
