-- ============================================================
-- 07_s3_export.sql
-- Zomato Data ETL & Analytics Pipeline
-- ============================================================
-- Purpose:
--   Export cleaned data, dimension tables and the fact table from
--   Snowflake back to AWS S3 as CSV files.
-- ============================================================

LIST @ZOMATO_PROJECT.RAW.MANAGE_STAGE;

COPY INTO @ZOMATO_PROJECT.RAW.MANAGE_STAGE/exports/zomato_clean
FROM ZOMATO_PROJECT.RAW.ZOMATO_CLEAN
FILE_FORMAT = (
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    COMPRESSION = NONE
)
HEADER = TRUE
OVERWRITE = TRUE;

LIST @ZOMATO_PROJECT.RAW.MANAGE_STAGE/exports;


COPY INTO @ZOMATO_PROJECT.RAW.MANAGE_STAGE/exports/dim_restaurant
FROM ZOMATO_PROJECT.RAW.DIM_RESTAURANT
FILE_FORMAT = (
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    COMPRESSION = NONE
)
HEADER = TRUE
OVERWRITE = TRUE;


COPY INTO @ZOMATO_PROJECT.RAW.MANAGE_STAGE/exports/dim_location
FROM ZOMATO_PROJECT.RAW.DIM_LOCATION
FILE_FORMAT = (
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    COMPRESSION = NONE
)
HEADER = TRUE
OVERWRITE = TRUE;

COPY INTO @ZOMATO_PROJECT.RAW.MANAGE_STAGE/exports/dim_cuisine
FROM ZOMATO_PROJECT.RAW.DIM_CUISINE
FILE_FORMAT = (
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    COMPRESSION = NONE
)
HEADER = TRUE
OVERWRITE = TRUE;

COPY INTO @ZOMATO_PROJECT.RAW.MANAGE_STAGE/exports/dim_type
FROM ZOMATO_PROJECT.RAW.DIM_TYPE
FILE_FORMAT = (
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    COMPRESSION = NONE
)
HEADER = TRUE
OVERWRITE = TRUE;

COPY INTO @ZOMATO_PROJECT.RAW.MANAGE_STAGE/exports/fact_restaurant
FROM ZOMATO_PROJECT.RAW.FACT_RESTAURANT
FILE_FORMAT = (
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    COMPRESSION = NONE
)
HEADER = TRUE
OVERWRITE = TRUE;

LIST @ZOMATO_PROJECT.RAW.MANAGE_STAGE/exports;

SELECT
    COUNT(*) AS TOTAL_ROWS
FROM ZOMATO_PROJECT.RAW.ZOMATO_CLEAN;

SELECT 'DIM_RESTAURANT' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM ZOMATO_PROJECT.RAW.DIM_RESTAURANT

UNION ALL

SELECT 'DIM_CUISINE', COUNT(*)
FROM ZOMATO_PROJECT.RAW.DIM_CUISINE

UNION ALL

SELECT 'DIM_LOCATION', COUNT(*)
FROM ZOMATO_PROJECT.RAW.DIM_LOCATION

UNION ALL

SELECT 'DIM_TYPE', COUNT(*)
FROM ZOMATO_PROJECT.RAW.DIM_TYPE

UNION ALL

SELECT 'FACT_RESTAURANT', COUNT(*)
FROM ZOMATO_PROJECT.RAW.FACT_RESTAURANT;

SELECT COUNT(*) AS ORPHAN_RESTAURANT_KEYS
FROM ZOMATO_PROJECT.RAW.FACT_RESTAURANT f
LEFT JOIN ZOMATO_PROJECT.RAW.DIM_RESTAURANT d
    ON f.RESTAURANT_ID = d.RESTAURANT_ID
WHERE d.RESTAURANT_ID IS NULL;

SELECT
    COUNT(*) AS TOTAL_FACT_ROWS,

    COUNT(d.RESTAURANT_ID) AS RESTAURANT_MATCHES,

    COUNT(c.CUISINE_ID) AS CUISINE_MATCHES,

    COUNT(l.LOCATION_ID) AS LOCATION_MATCHES,

    COUNT(t.TYPE_ID) AS TYPE_MATCHES

FROM ZOMATO_PROJECT.RAW.FACT_RESTAURANT f

LEFT JOIN ZOMATO_PROJECT.RAW.DIM_RESTAURANT d
    ON f.RESTAURANT_ID = d.RESTAURANT_ID

LEFT JOIN ZOMATO_PROJECT.RAW.DIM_CUISINE c
    ON f.CUISINE_ID = c.CUISINE_ID

LEFT JOIN ZOMATO_PROJECT.RAW.DIM_LOCATION l
    ON f.LOCATION_ID = l.LOCATION_ID

LEFT JOIN ZOMATO_PROJECT.RAW.DIM_TYPE t
    ON f.TYPE_ID = t.TYPE_ID;

    SELECT
    COUNT(*) AS TOTAL_RESTAURANTS,
    ROUND(AVG(f.RATING), 2) AS AVG_RATING,
    ROUND(AVG(f.VOTES), 0) AS AVG_VOTES,
    ROUND(AVG(f.APPROX_COST), 2) AS AVG_APPROX_COST
FROM ZOMATO_PROJECT.RAW.FACT_RESTAURANT f;
