CREATE DATABASE IF NOT EXISTS ZOMATO_PROJECT;
CREATE SCHEMA IF NOT EXISTS ZOMATO_PROJECT.RAW;

CREATE OR REPLACE STORAGE INTEGRATION ZOMATO_S3_INTEGRATION
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = S3
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::503789396713:role/ZomatoSnowflakeRole'
  STORAGE_ALLOWED_LOCATIONS = ('s3://zomato-bucket-1122/');

  DESC INTEGRATION ZOMATO_S3_INTEGRATION;

  ALTER STORAGE INTEGRATION ZOMATO_S3_INTEGRATION
SET STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::503789396713:role/ZomatoSnowflakeRole';

CREATE OR REPLACE STAGE ZOMATO_PROJECT.RAW.MANAGE_STAGE
  URL = 's3://zomato-bucket-1122/'
  STORAGE_INTEGRATION = ZOMATO_S3_INTEGRATION;

  DESC STAGE ZOMATO_PROJECT.RAW.MANAGE_STAGE;


  SELECT SYSTEM$VALIDATE_STORAGE_INTEGRATION(
    'ZOMATO_S3_INTEGRATION',
    's3://zomato-bucket-1122/',
    'zomato.csv',
    'read'
);

LIST @ZOMATO_PROJECT.RAW.MANAGE_STAGE;
LIST @RAW.ZOMATO_STAGE;

DESC STAGE ZOMATO_PROJECT.RAW.MANAGE_STAGE;

CREATE OR REPLACE FILE FORMAT ZOMATO_PROJECT.RAW.ZOMATO_CSV_FORMAT
  TYPE = 'CSV'
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  MULTI_LINE = TRUE
  TRIM_SPACE = TRUE
  NULL_IF = ('', 'NULL', 'null');


  SELECT
    t.$1,
    t.$2,
    t.$3,
    t.$4,
    t.$5,
    t.$6,
    t.$7,
    t.$8,
    t.$9,
    t.$10,
    t.$11,
    t.$12,
    t.$13,
    t.$14,
    t.$15,
    t.$16,
    t.$17
FROM @ZOMATO_PROJECT.RAW.MANAGE_STAGE/zomato.csv
(
    FILE_FORMAT => 'ZOMATO_PROJECT.RAW.ZOMATO_CSV_FORMAT'
) t
LIMIT 3;

CREATE OR REPLACE TABLE RAW.STAGE_RAW_DATA (
    URL             STRING,
    ADDRESS         STRING,
    NAME            STRING,
    ONLINE_ORDER    STRING,
    BOOK_TABLE      STRING,
    RATE            STRING,
    VOTES           STRING,
    PHONE           STRING,
    LOCATION        STRING,
    REST_TYPE       STRING,
    DISH_LIKED      STRING,
    CUISINES        STRING,
    APPROX_COST     STRING,
    REVIEWS_LIST    STRING,
    MENU_ITEM       STRING,
    LISTED_IN_TYPE  STRING,
    LISTED_IN_CITY  STRING
);

COPY INTO RAW.STAGE_RAW_DATA
FROM @RAW.MANAGE_STAGE/zomato.csv
FILE_FORMAT = (
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    MULTI_LINE = TRUE
)
ON_ERROR = 'ABORT_STATEMENT';

SELECT COUNT(*) AS TOTAL_ROWS
FROM RAW.STAGE_RAW_DATA;

SELECT *
FROM RAW.STAGE_RAW_DATA
LIMIT 5;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(NAME) AS NAME_FILLED,
    COUNT(CUISINES) AS CUISINES_FILLED,
    COUNT(RATE) AS RATE_FILLED,
    COUNT(VOTES) AS VOTES_FILLED,
    COUNT(APPROX_COST) AS COST_FILLED
FROM RAW.STAGE_RAW_DATA;

SELECT
    RATE,
    COUNT(*) AS ROW_COUNT
FROM RAW.STAGE_RAW_DATA
GROUP BY RATE
ORDER BY ROW_COUNT DESC
LIMIT 30;

SELECT
    APPROX_COST,
    COUNT(*) AS ROW_COUNT
FROM RAW.STAGE_RAW_DATA
GROUP BY APPROX_COST
ORDER BY ROW_COUNT DESC
LIMIT 20;

SELECT
    ONLINE_ORDER,
    BOOK_TABLE,
    COUNT(*) AS ROW_COUNT
FROM RAW.STAGE_RAW_DATA
GROUP BY ONLINE_ORDER, BOOK_TABLE
ORDER BY ROW_COUNT DESC;

SELECT
    RATE,
    COUNT(*) AS ROW_COUNT
FROM RAW.STAGE_RAW_DATA
GROUP BY RATE
ORDER BY ROW_COUNT DESC
LIMIT 30;

SELECT
    APPROX_COST,
    COUNT(*) AS ROW_COUNT
FROM RAW.STAGE_RAW_DATA
GROUP BY APPROX_COST
ORDER BY ROW_COUNT DESC
LIMIT 20;

CREATE OR REPLACE TABLE ZOMATO_CLEAN AS
SELECT
    URL,
    TRIM(ADDRESS) AS ADDRESS,
    TRIM(NAME) AS RESTAURANT_NAME,

    CASE
        WHEN LOWER(TRIM(ONLINE_ORDER)) = 'yes' THEN TRUE
        WHEN LOWER(TRIM(ONLINE_ORDER)) = 'no' THEN FALSE
        ELSE NULL
    END AS ONLINE_ORDER,

    CASE
        WHEN LOWER(TRIM(BOOK_TABLE)) = 'yes' THEN TRUE
        WHEN LOWER(TRIM(BOOK_TABLE)) = 'no' THEN FALSE
        ELSE NULL
    END AS BOOK_TABLE,

    CASE
        WHEN TRIM(RATE) IN ('', 'NEW') THEN NULL
        ELSE TRY_TO_NUMBER(
            SPLIT_PART(REPLACE(TRIM(RATE), ' ', ''), '/', 1)
        )
    END AS RATING,

    TRY_TO_NUMBER(
        REPLACE(TRIM(VOTES), ',', '')
    ) AS VOTES,

    TRIM(PHONE) AS PHONE,

    TRIM(LOCATION) AS LOCATION,

    TRIM(REST_TYPE) AS REST_TYPE,

    TRIM(DISH_LIKED) AS DISH_LIKED,

    TRIM(CUISINES) AS CUISINES,

    TRY_TO_NUMBER(
        REPLACE(TRIM(APPROX_COST), ',', '')
    ) AS APPROX_COST,

    REVIEWS_LIST,

    MENU_ITEM,

    TRIM(LISTED_IN_TYPE) AS LISTED_IN_TYPE,

    TRIM(LISTED_IN_CITY) AS LISTED_IN_CITY

FROM STAGE_RAW_DATA;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(RESTAURANT_NAME IS NOT NULL) AS NAME_FILLED,
    COUNT_IF(CUISINES IS NOT NULL) AS CUISINES_FILLED,
    COUNT_IF(RATING IS NOT NULL) AS RATING_FILLED,
    COUNT_IF(VOTES IS NOT NULL) AS VOTES_FILLED,
    COUNT_IF(APPROX_COST IS NOT NULL) AS COST_FILLED
FROM ZOMATO_CLEAN;


SELECT RATING, COUNT(*) AS ROW_COUNT
FROM ZOMATO_CLEAN
GROUP BY RATING
ORDER BY RATING DESC;

SELECT APPROX_COST, COUNT(*) AS ROW_COUNT
FROM ZOMATO_CLEAN
GROUP BY APPROX_COST
ORDER BY APPROX_COST;

DESC TABLE ZOMATO_CLEAN;

SELECT
    RATE,
    TRY_TO_DECIMAL(
        REGEXP_SUBSTR(TRIM(RATE), '[0-9]+(\.[0-9]+)?'),
        3,
        1
    ) AS TEST_RATING
FROM STAGE_RAW_DATA
WHERE TRIM(RATE) NOT IN ('', 'NEW')
LIMIT 30;


CREATE OR REPLACE TABLE ZOMATO_CLEAN AS
SELECT
    URL,
    TRIM(ADDRESS) AS ADDRESS,
    TRIM(NAME) AS RESTAURANT_NAME,

    CASE
        WHEN LOWER(TRIM(ONLINE_ORDER)) = 'yes' THEN TRUE
        WHEN LOWER(TRIM(ONLINE_ORDER)) = 'no' THEN FALSE
        ELSE NULL
    END AS ONLINE_ORDER,

    CASE
        WHEN LOWER(TRIM(BOOK_TABLE)) = 'yes' THEN TRUE
        WHEN LOWER(TRIM(BOOK_TABLE)) = 'no' THEN FALSE
        ELSE NULL
    END AS BOOK_TABLE,

    CASE
        WHEN TRIM(RATE) = '' OR UPPER(TRIM(RATE)) = 'NEW' THEN NULL
        ELSE TRY_TO_DECIMAL(
            REGEXP_SUBSTR(
                TRIM(RATE),
                '[0-9]+(\.[0-9]+)?'
            ),
            3,
            1
        )
    END AS RATING,

    TRY_TO_NUMBER(
        REPLACE(TRIM(VOTES), ',', '')
    ) AS VOTES,

    TRIM(PHONE) AS PHONE,
    TRIM(LOCATION) AS LOCATION,
    TRIM(REST_TYPE) AS REST_TYPE,
    TRIM(DISH_LIKED) AS DISH_LIKED,
    TRIM(CUISINES) AS CUISINES,

    TRY_TO_NUMBER(
        REPLACE(TRIM(APPROX_COST), ',', '')
    ) AS APPROX_COST,

    REVIEWS_LIST,
    MENU_ITEM,
    TRIM(LISTED_IN_TYPE) AS LISTED_IN_TYPE,
    TRIM(LISTED_IN_CITY) AS LISTED_IN_CITY

FROM STAGE_RAW_DATA;

SELECT
    RATING,
    COUNT(*) AS ROW_COUNT
FROM ZOMATO_CLEAN
GROUP BY RATING
ORDER BY RATING DESC;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(RATING) AS RATING_FILLED,
    COUNT(VOTES) AS VOTES_FILLED,
    COUNT(APPROX_COST) AS COST_FILLED,
    COUNT(CUISINES) AS CUISINES_FILLED
FROM ZOMATO_CLEAN;

DESCRIBE TABLE ZOMATO_CLEAN;

SELECT *
FROM ZOMATO_CLEAN
LIMIT 5;

// Create DIM_RESTAURANT

CREATE OR REPLACE TABLE DIM_RESTAURANT (
    RESTAURANT_ID INT AUTOINCREMENT PRIMARY KEY,
    URL STRING,
    RESTAURANT_NAME STRING,
    ADDRESS STRING,
    PHONE STRING
);

INSERT INTO DIM_RESTAURANT (
    URL,
    RESTAURANT_NAME,
    ADDRESS,
    PHONE
)
SELECT DISTINCT
    TRIM(URL),
    TRIM(RESTAURANT_NAME),
    TRIM(ADDRESS),
    TRIM(PHONE)
FROM ZOMATO_CLEAN
WHERE RESTAURANT_NAME IS NOT NULL;

SELECT COUNT(*) AS RESTAURANT_DIM_ROWS
FROM DIM_RESTAURANT;

SELECT *
FROM DIM_RESTAURANT
LIMIT 10;

//Dim_location

CREATE OR REPLACE TABLE DIM_LOCATION (
    LOCATION_ID INT AUTOINCREMENT PRIMARY KEY,
    LOCATION STRING,
    LISTED_IN_CITY STRING
);

INSERT INTO DIM_LOCATION (
    LOCATION,
    LISTED_IN_CITY
)
SELECT DISTINCT
    TRIM(LOCATION),
    TRIM(LISTED_IN_CITY)
FROM ZOMATO_CLEAN
WHERE LOCATION IS NOT NULL
   OR LISTED_IN_CITY IS NOT NULL;

   SELECT COUNT(*) AS LOCATION_DIM_ROWS
FROM DIM_LOCATION;

SELECT *
FROM DIM_LOCATION
LIMIT 10;

//DIM_CUISINE

CREATE OR REPLACE TABLE DIM_CUISINE (
    CUISINE_ID INT AUTOINCREMENT PRIMARY KEY,
    DISH_LIKED STRING,
    CUISINES STRING
);

INSERT INTO DIM_CUISINE (
    DISH_LIKED,
    CUISINES
)
SELECT DISTINCT
    TRIM(DISH_LIKED),
    TRIM(CUISINES)
FROM ZOMATO_CLEAN
WHERE DISH_LIKED IS NOT NULL
   OR CUISINES IS NOT NULL;

   SELECT COUNT(*) AS CUISINE_DIM_ROWS
FROM DIM_CUISINE;

SELECT *
FROM DIM_CUISINE
LIMIT 10;

//DIM_TYPE

CREATE OR REPLACE TABLE DIM_TYPE (
    TYPE_ID INT AUTOINCREMENT PRIMARY KEY,
    REST_TYPE STRING,
    LISTED_IN_TYPE STRING
);

INSERT INTO DIM_TYPE (
    REST_TYPE,
    LISTED_IN_TYPE
)
SELECT DISTINCT
    TRIM(REST_TYPE),
    TRIM(LISTED_IN_TYPE)
FROM ZOMATO_CLEAN
WHERE REST_TYPE IS NOT NULL
   OR LISTED_IN_TYPE IS NOT NULL;

   SELECT COUNT(*) AS TYPE_DIM_ROWS
FROM DIM_TYPE;

SELECT *
FROM DIM_TYPE
LIMIT 10;

//FACT table

CREATE OR REPLACE TABLE FACT_RESTAURANT (
    FACT_ID INT AUTOINCREMENT PRIMARY KEY,
    RESTAURANT_ID INT,
    LOCATION_ID INT,
    CUISINE_ID INT,
    TYPE_ID INT,

    ONLINE_ORDER BOOLEAN,
    BOOK_TABLE BOOLEAN,

    RATING NUMBER(3,1),
    VOTES NUMBER(38,0),
    APPROX_COST NUMBER(38,0)
);
//populate fact table

INSERT INTO FACT_RESTAURANT (
    RESTAURANT_ID,
    LOCATION_ID,
    CUISINE_ID,
    TYPE_ID,
    ONLINE_ORDER,
    BOOK_TABLE,
    RATING,
    VOTES,
    APPROX_COST
)
SELECT
    DR.RESTAURANT_ID,
    DL.LOCATION_ID,
    DC.CUISINE_ID,
    DT.TYPE_ID,

    Z.ONLINE_ORDER,
    Z.BOOK_TABLE,
    Z.RATING,
    Z.VOTES,
    Z.APPROX_COST

FROM ZOMATO_CLEAN Z

LEFT JOIN DIM_RESTAURANT DR
    ON TRIM(Z.URL) = DR.URL

LEFT JOIN DIM_LOCATION DL
    ON COALESCE(TRIM(Z.LOCATION), '') =
       COALESCE(DL.LOCATION, '')
   AND COALESCE(TRIM(Z.LISTED_IN_CITY), '') =
       COALESCE(DL.LISTED_IN_CITY, '')

LEFT JOIN DIM_CUISINE DC
    ON COALESCE(TRIM(Z.DISH_LIKED), '') =
       COALESCE(DC.DISH_LIKED, '')
   AND COALESCE(TRIM(Z.CUISINES), '') =
       COALESCE(DC.CUISINES, '')

LEFT JOIN DIM_TYPE DT
    ON COALESCE(TRIM(Z.REST_TYPE), '') =
       COALESCE(DT.REST_TYPE, '')
   AND COALESCE(TRIM(Z.LISTED_IN_TYPE), '') =
       COALESCE(DT.LISTED_IN_TYPE, '');

       SELECT COUNT(*) AS FACT_ROWS
FROM FACT_RESTAURANT;

SELECT *
FROM FACT_RESTAURANT
LIMIT 10;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(RESTAURANT_ID IS NULL) AS MISSING_RESTAURANT,
    COUNT_IF(LOCATION_ID IS NULL) AS MISSING_LOCATION,
    COUNT_IF(CUISINE_ID IS NULL) AS MISSING_CUISINE,
    COUNT_IF(TYPE_ID IS NULL) AS MISSING_TYPE
FROM FACT_RESTAURANT;

// Analytics Use Case 1: Top-Rated Restaurants
SELECT
    DR.RESTAURANT_NAME,
    DL.LOCATION,
    DC.CUISINES,
    FR.RATING,
    FR.VOTES,
    FR.APPROX_COST
FROM FACT_RESTAURANT FR
JOIN DIM_RESTAURANT DR
    ON FR.RESTAURANT_ID = DR.RESTAURANT_ID
LEFT JOIN DIM_LOCATION DL
    ON FR.LOCATION_ID = DL.LOCATION_ID
LEFT JOIN DIM_CUISINE DC
    ON FR.CUISINE_ID = DC.CUISINE_ID
WHERE FR.RATING IS NOT NULL
ORDER BY FR.RATING DESC, FR.VOTES DESC
LIMIT 20;


//Analytics Use Case 2: Best Restaurants Under ₹500
SELECT
    DR.RESTAURANT_NAME,
    DL.LOCATION,
    DC.CUISINES,
    FR.RATING,
    FR.VOTES,
    FR.APPROX_COST
FROM FACT_RESTAURANT FR
JOIN DIM_RESTAURANT DR
    ON FR.RESTAURANT_ID = DR.RESTAURANT_ID
LEFT JOIN DIM_LOCATION DL
    ON FR.LOCATION_ID = DL.LOCATION_ID
LEFT JOIN DIM_CUISINE DC
    ON FR.CUISINE_ID = DC.CUISINE_ID
WHERE FR.APPROX_COST <= 500
  AND FR.RATING IS NOT NULL
ORDER BY FR.RATING DESC, FR.VOTES DESC
LIMIT 20;

//Analytics Use Case 3: Online Order vs Table Booking

SELECT
    ONLINE_ORDER,
    BOOK_TABLE,
    COUNT(*) AS RESTAURANT_COUNT
FROM FACT_RESTAURANT
GROUP BY
    ONLINE_ORDER,
    BOOK_TABLE
ORDER BY RESTAURANT_COUNT DESC;

//Analytics Use Case 4: Restaurant Count by Location

SELECT
    DL.LOCATION,
    COUNT(*) AS RESTAURANT_COUNT
FROM FACT_RESTAURANT FR
JOIN DIM_LOCATION DL
    ON FR.LOCATION_ID = DL.LOCATION_ID
WHERE DL.LOCATION IS NOT NULL
GROUP BY DL.LOCATION
ORDER BY RESTAURANT_COUNT DESC
LIMIT 20;



SELECT *
FROM ZOMATO_PROJECT.RAW.ZOMATO_CLEAN
LIMIT 10;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(DISTINCT RESTAURANT_NAME || '|' || LOCATION) AS UNIQUE_RESTAURANT_LOCATIONS
FROM ZOMATO_PROJECT.RAW.ZOMATO_CLEAN;

CREATE OR REPLACE TABLE ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT AS
SELECT *
FROM ZOMATO_PROJECT.RAW.ZOMATO_CLEAN
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY RESTAURANT_NAME, LOCATION
    ORDER BY VOTES DESC
) = 1;
SELECT COUNT(*) AS UNIQUE_RESTAURANTS
FROM ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT;

SELECT
    COUNT(*) AS TOTAL_RESTAURANTS,
    COUNT(DISTINCT RESTAURANT_NAME) AS UNIQUE_NAMES,
    COUNT(DISTINCT LOCATION) AS UNIQUE_LOCATIONS
FROM ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT;

SELECT
    RESTAURANT_NAME,
    LOCATION,
    COUNT(*) AS CNT
FROM ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT
GROUP BY RESTAURANT_NAME, LOCATION
HAVING COUNT(*) > 1
ORDER BY CNT DESC;

//Use Case 1 — Online Order vs Table Booking

SELECT
    ONLINE_ORDER,
    BOOK_TABLE,
    COUNT(*) AS RESTAURANT_COUNT
FROM ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT
GROUP BY ONLINE_ORDER, BOOK_TABLE
ORDER BY RESTAURANT_COUNT DESC;

//use case 2 :Best value resturant 
 SELECT
    RESTAURANT_NAME,
    LOCATION,
    RATING,
    VOTES,
    APPROX_COST
FROM ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT
WHERE RATING >= 4.0
  AND VOTES >= 500
  AND APPROX_COST IS NOT NULL
ORDER BY
    APPROX_COST ASC,
    RATING DESC,
    VOTES DESC
LIMIT 20;

//Use Case 3 — Location with Most Restaurants
SELECT
    LOCATION,
    COUNT(*) AS RESTAURANT_COUNT,
    ROUND(AVG(RATING), 2) AS AVG_RATING,
    ROUND(AVG(APPROX_COST), 0) AS AVG_COST
FROM ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT
GROUP BY LOCATION
ORDER BY RESTAURANT_COUNT DESC
LIMIT 20;

//Use Case 4 — Best Locations by Rating

SELECT
    LOCATION,
    COUNT(*) AS RESTAURANT_COUNT,
    ROUND(AVG(RATING), 2) AS AVG_RATING
FROM ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT
WHERE RATING IS NOT NULL
GROUP BY LOCATION
HAVING COUNT(*) >= 20
ORDER BY AVG_RATING DESC
LIMIT 15;

//Use Case 5 — Online Ordering Adoption by Location
SELECT
    LOCATION,
    COUNT(*) AS TOTAL_RESTAURANTS,
    SUM(IFF(ONLINE_ORDER = TRUE, 1, 0)) AS ONLINE_ORDER_RESTAURANTS,
    ROUND(
        100.0 * SUM(IFF(ONLINE_ORDER = TRUE, 1, 0)) / COUNT(*),
        2
    ) AS ONLINE_ORDER_PERCENT
FROM ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT
GROUP BY LOCATION
HAVING COUNT(*) >= 20
ORDER BY ONLINE_ORDER_PERCENT DESC
LIMIT 20;

//Use Case 6 — Table Booking Adoption

SELECT
    LOCATION,
    COUNT(*) AS TOTAL_RESTAURANTS,
    SUM(IFF(BOOK_TABLE = TRUE, 1, 0)) AS BOOKING_RESTAURANTS,
    ROUND(
        100.0 * SUM(IFF(BOOK_TABLE = TRUE, 1, 0)) / COUNT(*),
        2
    ) AS BOOKING_PERCENT
FROM ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT
GROUP BY LOCATION
HAVING COUNT(*) >= 20
ORDER BY BOOKING_PERCENT DESC
LIMIT 20;

//Use Case 7 — Rating Distribution

SELECT
    RATING,
    COUNT(*) AS RESTAURANT_COUNT
FROM ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT
WHERE RATING IS NOT NULL
GROUP BY RATING
ORDER BY RATING DESC;

//Use Case 8 — Cost Segment Analysis
SELECT
    CASE
        WHEN APPROX_COST < 300 THEN 'Budget (<300)'
        WHEN APPROX_COST BETWEEN 300 AND 700 THEN 'Mid-Range (300-700)'
        WHEN APPROX_COST BETWEEN 701 AND 1200 THEN 'Premium (701-1200)'
        ELSE 'Luxury (>1200)'
    END AS COST_SEGMENT,

    COUNT(*) AS RESTAURANT_COUNT,
    ROUND(AVG(RATING), 2) AS AVG_RATING,
    ROUND(AVG(VOTES), 0) AS AVG_VOTES

FROM ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT
WHERE APPROX_COST IS NOT NULL
GROUP BY COST_SEGMENT
ORDER BY AVG_RATING DESC;

//Use Case 9 — Restaurant Type Performance
SELECT
    REST_TYPE,
    COUNT(*) AS RESTAURANT_COUNT,
    ROUND(AVG(RATING), 2) AS AVG_RATING,
    ROUND(AVG(APPROX_COST), 0) AS AVG_COST,
    ROUND(AVG(VOTES), 0) AS AVG_VOTES
FROM ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT
WHERE REST_TYPE IS NOT NULL
GROUP BY REST_TYPE
HAVING COUNT(*) >= 20
ORDER BY AVG_RATING DESC;

//Use Case 10 — Highly Rated but Affordable
SELECT
    RESTAURANT_NAME,
    LOCATION,
    REST_TYPE,
    RATING,
    VOTES,
    APPROX_COST
FROM ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT
WHERE RATING >= 4.5
  AND APPROX_COST <= 500
  AND VOTES >= 100
ORDER BY RATING DESC, VOTES DESC, APPROX_COST ASC
LIMIT 25;

LIST @ZOMATO_PROJECT.RAW.MANAGE_STAGE;

COPY INTO @ZOMATO_PROJECT.RAW.MANAGE_STAGE/exports/zomato_clean
FROM ZOMATO_PROJECT.RAW.ZOMATO_CLEAN
FILE_FORMAT = (
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    COMPRESSION = NONE
)
HEADER = TRUE
OVERWRITE = TRUE;

LIST @ZOMATO_PROJECT.RAW.MANAGE_STAGE/exports;


COPY INTO @ZOMATO_PROJECT.RAW.MANAGE_STAGE/exports/dim_restaurant
FROM ZOMATO_PROJECT.RAW.DIM_RESTAURANT
FILE_FORMAT = (
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    COMPRESSION = NONE
)
HEADER = TRUE
OVERWRITE = TRUE;


COPY INTO @ZOMATO_PROJECT.RAW.MANAGE_STAGE/exports/dim_location
FROM ZOMATO_PROJECT.RAW.DIM_LOCATION
FILE_FORMAT = (
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    COMPRESSION = NONE
)
HEADER = TRUE
OVERWRITE = TRUE;

COPY INTO @ZOMATO_PROJECT.RAW.MANAGE_STAGE/exports/dim_cuisine
FROM ZOMATO_PROJECT.RAW.DIM_CUISINE
FILE_FORMAT = (
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    COMPRESSION = NONE
)
HEADER = TRUE
OVERWRITE = TRUE;

COPY INTO @ZOMATO_PROJECT.RAW.MANAGE_STAGE/exports/dim_type
FROM ZOMATO_PROJECT.RAW.DIM_TYPE
FILE_FORMAT = (
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    COMPRESSION = NONE
)
HEADER = TRUE
OVERWRITE = TRUE;

COPY INTO @ZOMATO_PROJECT.RAW.MANAGE_STAGE/exports/fact_restaurant
FROM ZOMATO_PROJECT.RAW.FACT_RESTAURANT
FILE_FORMAT = (
    TYPE = CSV
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    COMPRESSION = NONE
)
HEADER = TRUE
OVERWRITE = TRUE;

LIST @ZOMATO_PROJECT.RAW.MANAGE_STAGE/exports;

SELECT
    COUNT(*) AS TOTAL_ROWS
FROM ZOMATO_PROJECT.RAW.ZOMATO_CLEAN;

SELECT 'DIM_RESTAURANT' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM ZOMATO_PROJECT.RAW.DIM_RESTAURANT

UNION ALL

SELECT 'DIM_CUISINE', COUNT(*)
FROM ZOMATO_PROJECT.RAW.DIM_CUISINE

UNION ALL

SELECT 'DIM_LOCATION', COUNT(*)
FROM ZOMATO_PROJECT.RAW.DIM_LOCATION

UNION ALL

SELECT 'DIM_TYPE', COUNT(*)
FROM ZOMATO_PROJECT.RAW.DIM_TYPE

UNION ALL

SELECT 'FACT_RESTAURANT', COUNT(*)
FROM ZOMATO_PROJECT.RAW.FACT_RESTAURANT;

SELECT COUNT(*) AS ORPHAN_RESTAURANT_KEYS
FROM ZOMATO_PROJECT.RAW.FACT_RESTAURANT f
LEFT JOIN ZOMATO_PROJECT.RAW.DIM_RESTAURANT d
    ON f.RESTAURANT_ID = d.RESTAURANT_ID
WHERE d.RESTAURANT_ID IS NULL;

SELECT
    COUNT(*) AS TOTAL_FACT_ROWS,

    COUNT(d.RESTAURANT_ID) AS RESTAURANT_MATCHES,

    COUNT(c.CUISINE_ID) AS CUISINE_MATCHES,

    COUNT(l.LOCATION_ID) AS LOCATION_MATCHES,

    COUNT(t.TYPE_ID) AS TYPE_MATCHES

FROM ZOMATO_PROJECT.RAW.FACT_RESTAURANT f

LEFT JOIN ZOMATO_PROJECT.RAW.DIM_RESTAURANT d
    ON f.RESTAURANT_ID = d.RESTAURANT_ID

LEFT JOIN ZOMATO_PROJECT.RAW.DIM_CUISINE c
    ON f.CUISINE_ID = c.CUISINE_ID

LEFT JOIN ZOMATO_PROJECT.RAW.DIM_LOCATION l
    ON f.LOCATION_ID = l.LOCATION_ID

LEFT JOIN ZOMATO_PROJECT.RAW.DIM_TYPE t
    ON f.TYPE_ID = t.TYPE_ID;

    SELECT
    COUNT(*) AS TOTAL_RESTAURANTS,
    ROUND(AVG(f.RATING), 2) AS AVG_RATING,
    ROUND(AVG(f.VOTES), 0) AS AVG_VOTES,
    ROUND(AVG(f.APPROX_COST), 2) AS AVG_APPROX_COST
FROM ZOMATO_PROJECT.RAW.FACT_RESTAURANT f;