SELECT *
FROM ZOMATO_PROJECT.ANALYTICS.VW_OVERALL_KPIS;

CREATE OR REPLACE VIEW ZOMATO_PROJECT.ANALYTICS.VW_LOCATION_ANALYSIS AS
SELECT
    l.LOCATION,
    COUNT(*) AS RESTAURANT_COUNT,
    ROUND(AVG(f.RATING), 2) AS AVG_RATING,
    ROUND(AVG(f.APPROX_COST), 2) AS AVG_COST,
    SUM(f.VOTES) AS TOTAL_VOTES
FROM ZOMATO_PROJECT.RAW.FACT_RESTAURANT f
JOIN ZOMATO_PROJECT.RAW.DIM_LOCATION l
    ON f.LOCATION_ID = l.LOCATION_ID
GROUP BY l.LOCATION
ORDER BY RESTAURANT_COUNT DESC;

SELECT *
FROM ZOMATO_PROJECT.ANALYTICS.VW_LOCATION_ANALYSIS;


CREATE OR REPLACE VIEW ZOMATO_PROJECT.ANALYTICS.VW_CUISINE_ANALYSIS AS
SELECT
    c.CUISINES,
    COUNT(*) AS RESTAURANT_COUNT,
    ROUND(AVG(f.RATING), 2) AS AVG_RATING,
    ROUND(AVG(f.APPROX_COST), 2) AS AVG_COST,
    SUM(f.VOTES) AS TOTAL_VOTES
FROM ZOMATO_PROJECT.RAW.FACT_RESTAURANT f
JOIN ZOMATO_PROJECT.RAW.DIM_CUISINE c
    ON f.CUISINE_ID = c.CUISINE_ID
GROUP BY c.CUISINES
ORDER BY RESTAURANT_COUNT DESC;

SELECT *
FROM ZOMATO_PROJECT.ANALYTICS.VW_CUISINE_ANALYSIS;

CREATE OR REPLACE VIEW ZOMATO_PROJECT.ANALYTICS.VW_COST_ANALYSIS AS
SELECT
    f.APPROX_COST,
    COUNT(*) AS RESTAURANT_COUNT,
    ROUND(AVG(f.RATING), 2) AS AVG_RATING,
    SUM(f.VOTES) AS TOTAL_VOTES
FROM ZOMATO_PROJECT.RAW.FACT_RESTAURANT f
GROUP BY f.APPROX_COST
ORDER BY f.APPROX_COST;

SELECT *
FROM ZOMATO_PROJECT.ANALYTICS.VW_COST_ANALYSIS;

CREATE OR REPLACE VIEW ZOMATO_PROJECT.ANALYTICS.VW_RATING_ANALYSIS AS
SELECT
    f.RATING,
    COUNT(*) AS RESTAURANT_COUNT,
    ROUND(AVG(f.APPROX_COST), 2) AS AVG_COST,
    SUM(f.VOTES) AS TOTAL_VOTES
FROM ZOMATO_PROJECT.RAW.FACT_RESTAURANT f
GROUP BY f.RATING
ORDER BY f.RATING DESC;

SELECT *
FROM ZOMATO_PROJECT.ANALYTICS.VW_RATING_ANALYSIS;

CREATE OR REPLACE VIEW ZOMATO_PROJECT.ANALYTICS.VW_VOTE_ANALYSIS AS
SELECT
    CASE
        WHEN f.VOTES = 0 THEN 'No Votes'
        WHEN f.VOTES < 100 THEN 'Low Votes'
        WHEN f.VOTES < 500 THEN 'Medium Votes'
        WHEN f.VOTES < 1000 THEN 'High Votes'
        ELSE 'Very High Votes'
    END AS VOTE_CATEGORY,
    COUNT(*) AS RESTAURANT_COUNT,
    ROUND(AVG(f.RATING), 2) AS AVG_RATING,
    ROUND(AVG(f.APPROX_COST), 2) AS AVG_COST,
    SUM(f.VOTES) AS TOTAL_VOTES
FROM ZOMATO_PROJECT.RAW.FACT_RESTAURANT f
GROUP BY
    CASE
        WHEN f.VOTES = 0 THEN 'No Votes'
        WHEN f.VOTES < 100 THEN 'Low Votes'
        WHEN f.VOTES < 500 THEN 'Medium Votes'
        WHEN f.VOTES < 1000 THEN 'High Votes'
        ELSE 'Very High Votes'
    END
ORDER BY TOTAL_VOTES DESC;

CREATE OR REPLACE VIEW ZOMATO_PROJECT.ANALYTICS.VW_RESTAURANT_TYPE_ANALYSIS AS
SELECT
    t.REST_TYPE,
    t.LISTED_IN_TYPE,
    COUNT(*) AS RESTAURANT_COUNT,
    ROUND(AVG(f.RATING), 2) AS AVG_RATING,
    ROUND(AVG(f.APPROX_COST), 2) AS AVG_COST,
    SUM(f.VOTES) AS TOTAL_VOTES
FROM ZOMATO_PROJECT.RAW.FACT_RESTAURANT f
JOIN ZOMATO_PROJECT.RAW.DIM_TYPE t
    ON f.TYPE_ID = t.TYPE_ID
GROUP BY
    t.REST_TYPE,
    t.LISTED_IN_TYPE
ORDER BY RESTAURANT_COUNT DESC;

CREATE OR REPLACE VIEW ZOMATO_PROJECT.ANALYTICS.VW_ONLINE_ORDER_ANALYSIS AS
SELECT
    f.ONLINE_ORDER,
    COUNT(*) AS RESTAURANT_COUNT,
    ROUND(AVG(f.RATING), 2) AS AVG_RATING,
    ROUND(AVG(f.APPROX_COST), 2) AS AVG_COST,
    SUM(f.VOTES) AS TOTAL_VOTES
FROM ZOMATO_PROJECT.RAW.FACT_RESTAURANT f
GROUP BY f.ONLINE_ORDER
ORDER BY RESTAURANT_COUNT DESC;

DESC TABLE ZOMATO_PROJECT.RAW.FACT_RESTAURANT;

CREATE OR REPLACE VIEW ZOMATO_PROJECT.ANALYTICS.VW_TABLE_BOOKING_ANALYSIS AS
SELECT
    f.BOOK_TABLE,
    COUNT(*) AS RESTAURANT_COUNT,
    ROUND(AVG(f.RATING), 2) AS AVG_RATING,
    ROUND(AVG(f.APPROX_COST), 2) AS AVG_COST,
    SUM(f.VOTES) AS TOTAL_VOTES
FROM ZOMATO_PROJECT.RAW.FACT_RESTAURANT f
GROUP BY f.BOOK_TABLE
ORDER BY RESTAURANT_COUNT DESC;

CREATE OR REPLACE VIEW ZOMATO_PROJECT.ANALYTICS.VW_ONLINE_ORDER_VS_BOOKING AS
SELECT
    f.ONLINE_ORDER,
    f.BOOK_TABLE,
    COUNT(*) AS RESTAURANT_COUNT,
    ROUND(AVG(f.RATING), 2) AS AVG_RATING,
    ROUND(AVG(f.APPROX_COST), 2) AS AVG_COST,
    SUM(f.VOTES) AS TOTAL_VOTES
FROM ZOMATO_PROJECT.RAW.FACT_RESTAURANT f
GROUP BY
    f.ONLINE_ORDER,
    f.BOOK_TABLE
ORDER BY RESTAURANT_COUNT DESC;


CREATE OR REPLACE VIEW ZOMATO_PROJECT.ANALYTICS.VW_TOP_LOCATIONS AS
SELECT
    l.LOCATION,
    COUNT(*) AS RESTAURANT_COUNT
FROM ZOMATO_PROJECT.RAW.FACT_RESTAURANT f
JOIN ZOMATO_PROJECT.RAW.DIM_LOCATION l
    ON f.LOCATION_ID = l.LOCATION_ID
WHERE l.LOCATION IS NOT NULL
GROUP BY l.LOCATION
ORDER BY RESTAURANT_COUNT DESC
LIMIT 20;

CREATE OR REPLACE VIEW ZOMATO_PROJECT.ANALYTICS.VW_BEST_LOCATIONS AS
SELECT
    l.LOCATION,
    COUNT(*) AS RESTAURANT_COUNT,
    ROUND(AVG(f.RATING), 2) AS AVG_RATING
FROM ZOMATO_PROJECT.RAW.FACT_RESTAURANT f
JOIN ZOMATO_PROJECT.RAW.DIM_LOCATION l
    ON f.LOCATION_ID = l.LOCATION_ID
WHERE f.RATING IS NOT NULL
GROUP BY l.LOCATION
HAVING COUNT(*) >= 20
ORDER BY AVG_RATING DESC
LIMIT 15;

CREATE OR REPLACE VIEW ZOMATO_PROJECT.ANALYTICS.VW_CUISINE_PERFORMANCE AS
SELECT
    c.CUISINES,
    COUNT(*) AS RESTAURANT_COUNT,
    ROUND(AVG(f.RATING), 2) AS AVG_RATING,
    SUM(f.VOTES) AS TOTAL_VOTES
FROM ZOMATO_PROJECT.RAW.FACT_RESTAURANT f
JOIN ZOMATO_PROJECT.RAW.DIM_CUISINE c
    ON f.CUISINE_ID = c.CUISINE_ID
WHERE f.RATING IS NOT NULL
GROUP BY c.CUISINES
HAVING COUNT(*) >= 10
ORDER BY AVG_RATING DESC
LIMIT 20;

CREATE OR REPLACE VIEW ZOMATO_PROJECT.ANALYTICS.VW_VOTES_BY_LOCATION AS
SELECT
    l.LOCATION,
    SUM(f.VOTES) AS TOTAL_VOTES,
    ROUND(AVG(f.RATING), 2) AS AVG_RATING,
    COUNT(*) AS RESTAURANT_COUNT
FROM ZOMATO_PROJECT.RAW.FACT_RESTAURANT f
JOIN ZOMATO_PROJECT.RAW.DIM_LOCATION l
    ON f.LOCATION_ID = l.LOCATION_ID
GROUP BY l.LOCATION
ORDER BY TOTAL_VOTES DESC
LIMIT 20;

CREATE OR REPLACE VIEW ZOMATO_PROJECT.ANALYTICS.VW_TOP_RATED_RESTAURANTS AS
SELECT
    DR.RESTAURANT_NAME,
    DL.LOCATION,
    DC.CUISINES,
    FR.RATING,
    FR.VOTES,
    FR.APPROX_COST
FROM ZOMATO_PROJECT.RAW.FACT_RESTAURANT FR
JOIN ZOMATO_PROJECT.RAW.DIM_RESTAURANT DR
    ON FR.RESTAURANT_ID = DR.RESTAURANT_ID
LEFT JOIN ZOMATO_PROJECT.RAW.DIM_LOCATION DL
    ON FR.LOCATION_ID = DL.LOCATION_ID
LEFT JOIN ZOMATO_PROJECT.RAW.DIM_CUISINE DC
    ON FR.CUISINE_ID = DC.CUISINE_ID
WHERE FR.RATING IS NOT NULL
ORDER BY FR.RATING DESC, FR.VOTES DESC
LIMIT 20;

SELECT
    DR.RESTAURANT_NAME,
    DL.LOCATION,
    DC.CUISINES,
    FR.RATING,
    FR.VOTES,
    FR.APPROX_COST
FROM ZOMATO_PROJECT.RAW.FACT_RESTAURANT FR
JOIN ZOMATO_PROJECT.RAW.DIM_RESTAURANT DR
    ON FR.RESTAURANT_ID = DR.RESTAURANT_ID
LEFT JOIN ZOMATO_PROJECT.RAW.DIM_LOCATION DL
    ON FR.LOCATION_ID = DL.LOCATION_ID
LEFT JOIN ZOMATO_PROJECT.RAW.DIM_CUISINE DC
    ON FR.CUISINE_ID = DC.CUISINE_ID
WHERE FR.APPROX_COST <= 500
  AND FR.RATING IS NOT NULL
ORDER BY FR.RATING DESC, FR.VOTES DESC
LIMIT 20;

SELECT
    LOCATION,
    COUNT(*) AS TOTAL_RESTAURANTS,
    SUM(IFF(ONLINE_ORDER = TRUE, 1, 0)) AS ONLINE_ORDER_RESTAURANTS,
    ROUND(
        100.0 * SUM(IFF(ONLINE_ORDER = TRUE, 1, 0)) / COUNT(*),
        2
    ) AS ONLINE_ORDER_PERCENT
FROM ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT
GROUP BY LOCATION
HAVING COUNT(*) >= 20
ORDER BY ONLINE_ORDER_PERCENT DESC
LIMIT 20;

SELECT
    l.LOCATION,
    COUNT(*) AS TOTAL_RESTAURANTS,
    SUM(IFF(f.BOOK_TABLE = TRUE, 1, 0)) AS BOOKING_RESTAURANTS,
    ROUND(
        100.0 * SUM(IFF(f.BOOK_TABLE = TRUE, 1, 0)) / COUNT(*),
        2
    ) AS BOOKING_PERCENT
FROM ZOMATO_PROJECT.RAW.FACT_RESTAURANT f
JOIN ZOMATO_PROJECT.RAW.DIM_LOCATION l
    ON f.LOCATION_ID = l.LOCATION_ID
GROUP BY l.LOCATION
HAVING COUNT(*) >= 20
ORDER BY BOOKING_PERCENT DESC
LIMIT 20;

SELECT
    RATING,
    COUNT(*) AS RESTAURANT_COUNT
FROM ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT
WHERE RATING IS NOT NULL
GROUP BY RATING
ORDER BY RATING DESC;

SELECT
    CASE
        WHEN APPROX_COST < 300 THEN 'Budget (<300)'
        WHEN APPROX_COST BETWEEN 300 AND 700 THEN 'Mid-Range (300-700)'
        WHEN APPROX_COST BETWEEN 701 AND 1200 THEN 'Premium (701-1200)'
        ELSE 'Luxury (>1200)'
    END AS COST_SEGMENT,

    COUNT(*) AS RESTAURANT_COUNT,
    ROUND(AVG(RATING), 2) AS AVG_RATING,
    ROUND(AVG(VOTES), 0) AS AVG_VOTES

FROM ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT
WHERE APPROX_COST IS NOT NULL
GROUP BY COST_SEGMENT
ORDER BY AVG_RATING DESC;

SELECT
    CASE
        WHEN APPROX_COST < 300 THEN 'Budget (<300)'
        WHEN APPROX_COST BETWEEN 300 AND 700 THEN 'Mid-Range (300-700)'
        WHEN APPROX_COST BETWEEN 701 AND 1200 THEN 'Premium (701-1200)'
        ELSE 'Luxury (>1200)'
    END AS COST_SEGMENT,
    COUNT(*) AS RESTAURANT_COUNT,
    SUM(VOTES) AS TOTAL_VOTES
FROM ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT
WHERE APPROX_COST IS NOT NULL
GROUP BY COST_SEGMENT
ORDER BY RESTAURANT_COUNT DESC;

SELECT
    REST_TYPE,
    COUNT(*) AS RESTAURANT_COUNT,
    ROUND(AVG(RATING), 2) AS AVG_RATING,
    ROUND(AVG(APPROX_COST), 0) AS AVG_COST,
    ROUND(AVG(VOTES), 0) AS AVG_VOTES
FROM ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT
WHERE REST_TYPE IS NOT NULL
GROUP BY REST_TYPE
HAVING COUNT(*) >= 20
ORDER BY AVG_RATING DESC;

SELECT
    ONLINE_ORDER,
    COUNT(*) AS RESTAURANT_COUNT,
    ROUND(AVG(RATING), 2) AS AVG_RATING,
    ROUND(AVG(APPROX_COST), 0) AS AVG_COST,
    SUM(VOTES) AS TOTAL_VOTES
FROM ZOMATO_PROJECT.RAW.FACT_RESTAURANT
GROUP BY ONLINE_ORDER
ORDER BY RESTAURANT_COUNT DESC;

SELECT
    RESTAURANT_NAME,
    LOCATION,
    REST_TYPE,
    RATING,
    VOTES,
    APPROX_COST
FROM ZOMATO_PROJECT.RAW.ZOMATO_RESTAURANT
WHERE RATING >= 4.5
  AND APPROX_COST <= 500
  AND VOTES >= 100
ORDER BY RATING DESC, VOTES DESC, APPROX_COST ASC
LIMIT 25;

SELECT CURRENT_WAREHOUSE();

SELECT CURRENT_USER();